#pragma once

#include <algorithm>
#include <array>
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/split.hpp>
#include <boost/algorithm/string/trim.hpp>
#include <cassert>
#include <chrono>
#include <fstream>
#include <iostream>
#include <list>
#include <map>
#include <numeric>
#include <ranges>
#include <regex>
#include <stack>
#include <string>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <vector>

#include "aoc_util.h"
#include "ctre.hpp"
#include "fmt/core.h"
#include "fmt/ranges.h"
#include "itertools.hpp"
#include "scn/scn.h"
#include "scn/tuple_return.h"
#include "zip_longest.hpp"
